### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by jyotman** [eladnava/mongomonitor#1]
Having an option to post to a Slack webhook on errors would be really beneficial alongside the email option.

**Comment by eladnava** [comment]
@jyotman I like this idea a lot! 👍 

How about this package, seems perfect for the task at hand?
https://www.npmjs.com/package/slack-webhook

**Comment by jyotman** [comment]
Absolutely! Exactly what I had in mind. :+1:

**Comment by eladnava** [comment]
On second thought, might be better to use the officially supported Slack SDK:
https://github.com/slackapi/node-slack-sdk

This is how a message is posted to a webhook:
https://github.com/slackapi/node-slack-sdk#posting-a-message-with-incoming-webhooks

Would you like to submit a PR? 😄

**Comment by jyotman** [comment]
@eladnava cool! Will submit a PR soon :smiley:

**Comment by eladnava** [comment]
Closed via #2.
