### ISSUE TITLE
Keep the process running background

### ISSUE THREAD

**Issue by jyotman** [eladnava/mongomonitor#4]
In the docs it mentions 

> Leave the tool running on a remote server by executing the following command: 
```mongomonitor &```

But If we start the process this way on a remote server through a SSH session then as soon as we stop the session, the mongomonitor node process also stops because when the process tries to log to stdout or stderr, its not able because the session has been ended by us. More info about this issue is [here](http://stackoverflow.com/a/32029341/4440874).

The solution is pipe the logs to some place other than the terminal like this - 

    mongomonitor > /tmp/out.log 2> /tmp/error.log &

This works fine as I've tested and should be the bare minimum setup to use mongomonitor. But I think the proper solution would be to advice people to run the process using a process manager like PM2 or systemd.

**Comment by eladnava** [comment]
Hi @jyotman,
Good point. Appreciate the research and testing you put into this.

Would you like to submit a PR updating the docs to the new command?

Also, would you like to add instructions on running this permanently with `forever` or `pm2`?

**Comment by jyotman** [comment]
Sure! Will submit a PR :+1:
